[[cat-nodeattrs]]
== cat nodeattrs

`nodeattrs` 命令显示自定义节点属性。
例如：

[source,js]
--------------------------------------------------
GET /_cat/nodeattrs?v
--------------------------------------------------
// CONSOLE

如下显示：

[source,txt]
--------------------------------------------------
node    host      ip        attr     value
EK_AsJb 127.0.0.1 127.0.0.1 testattr test
--------------------------------------------------
// TESTRESPONSE[s/EK_AsJb/.+/ _cat]

前几列（ `node` ， `host` ， `ip` ）为你提供每个节点的基本信息 `attr` 和 `value` 提供节点自定义属性，每行一个。

[float]
=== Columns

以下是现有标题的详尽列表可以传递给 `nodeattrs?h=` ，以便检索有序列中的相关详细信息。
如果未指定标题，则会显示标记为默认显示的标题。
如果指定了任何标题，则不使用默认值。

为了简洁，别名可以用来代替完整的标题名称。
除非指定了不同的顺序（例如，`h=attr,value` versus `h=value,attr` ），
否则列按照下面列出的顺序出现。

指定标题时，默认情况下标题不会放在输出中。
要在输出中显示标题，请使用详细模式（ `v` ）。
标题名称将与提供的值匹配（例如， `pid` 与 `p` ）。
例如：

[source,js]
--------------------------------------------------
GET /_cat/nodeattrs?v&h=name,pid,attr,value
--------------------------------------------------
// CONSOLE

显示如下：

[source,txt]
--------------------------------------------------
name    pid   attr     value
EK_AsJb 19566 testattr test
--------------------------------------------------
// TESTRESPONSE[s/EK_AsJb/.+/ s/19566/\\d*/ _cat]

[cols="<,<,<,<,<",options="header",subs="normal"]
|=======================================================================
|Header |Alias |Appear by Default |Description |Example
|`node`|`name`|Yes|Name of the node|DKDM97B
|`id` |`nodeId` |No |Unique node ID |k0zy
|`pid` |`p` |No |Process ID |13061
|`host` |`h` |Yes |Host name |n1
|`ip` |`i` |Yes |IP address |127.0.1.1
|`port` |`po` |No |Bound transport port |9300
|`attr` | `attr.name` | Yes | Attribute name | rack
|`value` | `attr.value` | Yes | Attribute value | rack123
|=======================================================================
